name: CI
on: [push, pull_request]
jobs:
  Core:
    name: Core tests with npm
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci

      - name: test
        run: npm run test

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build